use serde::{Deserialize, Serialize};
use std::path::Path;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FormatCategory {
    Audio,
    Video,
    Image,
    Document,
    Data,
    Model3D,
    Archive,
    Font,
    Subtitle,
    Unknown,
}
impl FormatCategory {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Audio => "Audio",
            Self::Video => "Video",
            Self::Image => "Image",
            Self::Document => "Document",
            Self::Data => "Data",
            Self::Model3D => "3D Model",
            Self::Archive => "Archive",
            Self::Font => "Font",
            Self::Subtitle => "Subtitle",
            Self::Unknown => "Unknown",
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct FormatInfo {
    pub ext: &'static str,
    pub name: &'static str,
    pub category: FormatCategory,
    pub mime: &'static str,
    pub suggested_targets: &'static [&'static str],
}
pub static VIDEO_RESOLUTIONS: &[(&str, &str)] = &[
    ("2160p", "3840x2160"),
    ("1080p", "1920x1080"),
    ("720p", "1280x720"),
    ("480p", "854x480"),
];
pub fn is_video_resolution_target(ext: &str) -> bool {
    let clean = ext.trim_start_matches('.').to_lowercase();
    if let Some(info) = find_format(&clean) {
        if info.category == FormatCategory::Video {
            return true;
        }
    }
    matches!(clean.as_str(), "gif" | "apng")
}
pub fn is_video_source(ext: &str) -> bool {
    let clean = ext.trim_start_matches('.').to_lowercase();
    if let Some(info) = find_format(&clean) {
        return info.category == FormatCategory::Video;
    }
    false
}
pub fn scale_target_for(ext: &str) -> &'static str {
    match ext.trim_start_matches('.').to_lowercase().as_str() {
        "cr2" | "cr3" | "nef" | "arw" | "dng" | "raf" | "orf" | "rw2" | "crw" | "pef" | "srw" | "srf" | "mrw" | "dcr" | "kdc" | "erf" | "mos" | "nrw" | "mef" | "x3f" | "3fr" | "rwl" => "jpg",
        "clip" => "png",
        "cur" => "ico",
        "bik" | "bik2" | "rm" | "rmvb" | "vc1" => "mp4",
        "dnxhd" | "prores" | "mxf" => "mov",
        "3g2" | "3gp" | "3gpp" | "f4v" | "dvr-ms" => "mp4",
        "divx" | "xvid" => "avi",
        _ => {
            if let Some(info) = find_format(ext) {
                return info.ext;
            }
            "png"
        }
    }
}
pub static FORMAT_DATABASE: &[FormatInfo] = &[
    FormatInfo { ext: "png", name: "Portable Network Graphics", category: FormatCategory::Image, mime: "image/png", suggested_targets: &["jpg", "webp", "avif", "bmp", "ico", "tiff", "tga", "qoi", "pdf"] },
    FormatInfo { ext: "jpg", name: "JPEG Image", category: FormatCategory::Image, mime: "image/jpeg", suggested_targets: &["png", "webp", "avif", "bmp", "ico", "tiff", "tga", "qoi", "pdf"] },
    FormatInfo { ext: "jpeg", name: "JPEG Image", category: FormatCategory::Image, mime: "image/jpeg", suggested_targets: &["png", "webp", "avif", "bmp", "ico", "tiff", "tga", "qoi", "pdf"] },
    FormatInfo { ext: "jfif", name: "JPEG File Interchange Format", category: FormatCategory::Image, mime: "image/jpeg", suggested_targets: &["png", "jpg", "webp", "bmp", "ico"] },
    FormatInfo { ext: "webp", name: "WebP Image", category: FormatCategory::Image, mime: "image/webp", suggested_targets: &["png", "jpg", "bmp", "ico", "tiff", "gif", "pdf"] },
    FormatInfo { ext: "avif", name: "AV1 Image File Format", category: FormatCategory::Image, mime: "image/avif", suggested_targets: &["png", "jpg", "webp", "bmp"] },
    FormatInfo { ext: "jxl", name: "JPEG XL Image", category: FormatCategory::Image, mime: "image/jxl", suggested_targets: &["png", "jpg", "webp"] },
    FormatInfo { ext: "gif", name: "Graphics Interchange Format", category: FormatCategory::Image, mime: "image/gif", suggested_targets: &["png", "webp", "mp4", "webm", "apng"] },
    FormatInfo { ext: "bmp", name: "Bitmap Image", category: FormatCategory::Image, mime: "image/bmp", suggested_targets: &["png", "jpg", "webp", "ico", "pdf"] },
    FormatInfo { ext: "ico", name: "Windows Icon", category: FormatCategory::Image, mime: "image/x-icon", suggested_targets: &["png", "jpg", "bmp", "webp"] },
    FormatInfo { ext: "cur", name: "Windows Cursor", category: FormatCategory::Image, mime: "image/x-icon", suggested_targets: &["png", "ico"] },
    FormatInfo { ext: "tiff", name: "Tagged Image File Format", category: FormatCategory::Image, mime: "image/tiff", suggested_targets: &["png", "jpg", "webp", "pdf", "bmp"] },
    FormatInfo { ext: "tif", name: "Tagged Image File Format", category: FormatCategory::Image, mime: "image/tiff", suggested_targets: &["png", "jpg", "webp", "pdf", "bmp"] },
    FormatInfo { ext: "tga", name: "Truevision TGA", category: FormatCategory::Image, mime: "image/x-tga", suggested_targets: &["png", "jpg", "webp", "bmp"] },
    FormatInfo { ext: "qoi", name: "Quite OK Image", category: FormatCategory::Image, mime: "image/qoi", suggested_targets: &["png", "jpg", "webp", "bmp"] },
    FormatInfo { ext: "svg", name: "Scalable Vector Graphics", category: FormatCategory::Image, mime: "image/svg+xml", suggested_targets: &["png", "jpg", "webp", "pdf", "ico", "bmp"] },
    FormatInfo { ext: "svgz", name: "Compressed SVG", category: FormatCategory::Image, mime: "image/svg+xml", suggested_targets: &["svg", "png", "jpg", "pdf"] },
    FormatInfo { ext: "dds", name: "DirectDraw Surface", category: FormatCategory::Image, mime: "image/vnd-ms.dds", suggested_targets: &["png", "jpg", "tga", "bmp"] },
    FormatInfo { ext: "psd", name: "Adobe Photoshop Document", category: FormatCategory::Image, mime: "image/vnd.adobe.photoshop", suggested_targets: &["png", "jpg", "webp", "pdf", "tiff"] },
    FormatInfo { ext: "psb", name: "Photoshop Big Document", category: FormatCategory::Image, mime: "image/vnd.adobe.photoshop", suggested_targets: &["png", "jpg", "tiff"] },
    FormatInfo { ext: "xcf", name: "GIMP Image", category: FormatCategory::Image, mime: "image/x-xcf", suggested_targets: &["png", "jpg", "webp", "pdf"] },
    FormatInfo { ext: "heic", name: "High Efficiency Image Container", category: FormatCategory::Image, mime: "image/heic", suggested_targets: &["jpg", "png", "webp", "pdf"] },
    FormatInfo { ext: "heif", name: "High Efficiency Image Format", category: FormatCategory::Image, mime: "image/heif", suggested_targets: &["jpg", "png", "webp", "pdf"] },
    FormatInfo { ext: "hif", name: "Canon HEIF", category: FormatCategory::Image, mime: "image/heif", suggested_targets: &["jpg", "png"] },
    FormatInfo { ext: "cr2", name: "Canon Raw 2", category: FormatCategory::Image, mime: "image/x-canon-cr2", suggested_targets: &["jpg", "png", "dng", "tiff"] },
    FormatInfo { ext: "cr3", name: "Canon Raw 3", category: FormatCategory::Image, mime: "image/x-canon-cr3", suggested_targets: &["jpg", "png", "dng", "tiff"] },
    FormatInfo { ext: "nef", name: "Nikon Electronic Format", category: FormatCategory::Image, mime: "image/x-nikon-nef", suggested_targets: &["jpg", "png", "dng", "tiff"] },
    FormatInfo { ext: "arw", name: "Sony Alpha Raw", category: FormatCategory::Image, mime: "image/x-sony-arw", suggested_targets: &["jpg", "png", "dng", "tiff"] },
    FormatInfo { ext: "dng", name: "Digital Negative", category: FormatCategory::Image, mime: "image/x-adobe-dng", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "raf", name: "Fuji Raw", category: FormatCategory::Image, mime: "image/x-fuji-raf", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "orf", name: "Olympus Raw", category: FormatCategory::Image, mime: "image/x-olympus-orf", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "rw2", name: "Panasonic Lumix Raw", category: FormatCategory::Image, mime: "image/x-panasonic-raw", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "exr", name: "OpenEXR Image", category: FormatCategory::Image, mime: "image/x-exr", suggested_targets: &["png", "jpg", "hdr", "tiff"] },
    FormatInfo { ext: "hdr", name: "Radiance HDR", category: FormatCategory::Image, mime: "image/vnd.radiance", suggested_targets: &["png", "exr", "tiff"] },
    FormatInfo { ext: "ppm", name: "Portable Pixmap", category: FormatCategory::Image, mime: "image/x-portable-pixmap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "pgm", name: "Portable Graymap", category: FormatCategory::Image, mime: "image/x-portable-graymap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "pbm", name: "Portable Bitmap", category: FormatCategory::Image, mime: "image/x-portable-bitmap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "pnm", name: "Portable Anymap", category: FormatCategory::Image, mime: "image/x-portable-anymap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "pam", name: "Portable Arbitrary Map", category: FormatCategory::Image, mime: "image/x-portable-arbitrarymap", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "pcx", name: "Picture Exchange", category: FormatCategory::Image, mime: "image/x-pcx", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "icns", name: "Apple Icon Image", category: FormatCategory::Image, mime: "image/x-icns", suggested_targets: &["png", "ico", "jpg"] },
    FormatInfo { ext: "eps", name: "Encapsulated PostScript", category: FormatCategory::Image, mime: "application/postscript", suggested_targets: &["pdf", "png", "svg", "jpg"] },
    FormatInfo { ext: "ai", name: "Adobe Illustrator Artwork", category: FormatCategory::Image, mime: "application/illustrator", suggested_targets: &["pdf", "svg", "png"] },
    FormatInfo { ext: "farbfeld", name: "Farbfeld Lossless Image", category: FormatCategory::Image, mime: "image/x-farbfeld", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "crw", name: "Canon Raw CIFF", category: FormatCategory::Image, mime: "image/x-canon-crw", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "pef", name: "Pentax Electronic File", category: FormatCategory::Image, mime: "image/x-pentax-pef", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "srw", name: "Samsung Raw", category: FormatCategory::Image, mime: "image/x-samsung-srw", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "srf", name: "Sony Raw File", category: FormatCategory::Image, mime: "image/x-sony-srf", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "mrw", name: "Minolta Raw", category: FormatCategory::Image, mime: "image/x-minolta-mrw", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "dcr", name: "Kodak Digital Camera Raw", category: FormatCategory::Image, mime: "image/x-kodak-dcr", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "kdc", name: "Kodak DC Raw", category: FormatCategory::Image, mime: "image/x-kodak-kdc", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "erf", name: "Epson Raw File", category: FormatCategory::Image, mime: "image/x-epson-erf", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "mos", name: "Leaf Mosaic Raw", category: FormatCategory::Image, mime: "image/x-leaf-mos", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "nrw", name: "Nikon Raw (Coolpix)", category: FormatCategory::Image, mime: "image/x-nikon-nrw", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "mef", name: "Mamiya Electronic Format", category: FormatCategory::Image, mime: "image/x-mamiya-mef", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "x3f", name: "Sigma X3F Raw", category: FormatCategory::Image, mime: "image/x-sigma-x3f", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "3fr", name: "Hasselblad 3FR Raw", category: FormatCategory::Image, mime: "image/x-hasselblad-3fr", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "rwl", name: "Leica Raw", category: FormatCategory::Image, mime: "image/x-leica-rwl", suggested_targets: &["jpg", "png", "tiff"] },
    FormatInfo { ext: "cdr", name: "CorelDRAW Image", category: FormatCategory::Image, mime: "image/x-coreldraw", suggested_targets: &["pdf", "svg", "png", "jpg"] },
    FormatInfo { ext: "kra", name: "Krita Document", category: FormatCategory::Image, mime: "image/x-krita", suggested_targets: &["png", "jpg", "webp", "pdf"] },
    FormatInfo { ext: "clip", name: "Clip Studio Paint", category: FormatCategory::Image, mime: "image/x-clip", suggested_targets: &["png", "jpg", "psd"] },
    FormatInfo { ext: "emf", name: "Enhanced Metafile", category: FormatCategory::Image, mime: "image/x-emf", suggested_targets: &["png", "jpg", "svg", "pdf"] },
    FormatInfo { ext: "wmf", name: "Windows Metafile", category: FormatCategory::Image, mime: "image/x-wmf", suggested_targets: &["png", "jpg", "svg", "pdf"] },
    FormatInfo { ext: "pic", name: "Softimage PIC Image", category: FormatCategory::Image, mime: "image/x-pic", suggested_targets: &["png", "jpg", "tiff"] },
    FormatInfo { ext: "fits", name: "Flexible Image Transport", category: FormatCategory::Image, mime: "image/x-fits", suggested_targets: &["png", "jpg", "tiff"] },
    FormatInfo { ext: "ktx", name: "Khronos Texture", category: FormatCategory::Image, mime: "image/ktx", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "ktx2", name: "Khronos Texture 2", category: FormatCategory::Image, mime: "image/ktx2", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "pvr", name: "PowerVR Texture", category: FormatCategory::Image, mime: "image/x-pvr", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "astc", name: "ASTC Texture", category: FormatCategory::Image, mime: "image/x-astc", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "vtf", name: "Valve Texture Format", category: FormatCategory::Image, mime: "image/x-vtf", suggested_targets: &["png", "jpg", "tga"] },
    FormatInfo { ext: "sgi", name: "Silicon Graphics Image", category: FormatCategory::Image, mime: "image/x-sgi", suggested_targets: &["png", "jpg", "tiff"] },
    FormatInfo { ext: "rgb", name: "SGI RGB Image", category: FormatCategory::Image, mime: "image/x-rgb", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "rgba", name: "SGI RGBA Image", category: FormatCategory::Image, mime: "image/x-rgba", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "bw", name: "SGI Black and White", category: FormatCategory::Image, mime: "image/x-bw", suggested_targets: &["png", "jpg"] },
    FormatInfo { ext: "ras", name: "Sun Raster Image", category: FormatCategory::Image, mime: "image/x-sun-raster", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "sun", name: "Sun Raster Image", category: FormatCategory::Image, mime: "image/x-sun-raster", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "xbm", name: "X Bitmap", category: FormatCategory::Image, mime: "image/x-xbitmap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "xpm", name: "X Pixmap", category: FormatCategory::Image, mime: "image/x-xpixmap", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "wbmp", name: "Wireless Bitmap", category: FormatCategory::Image, mime: "image/vnd.wap.wbmp", suggested_targets: &["png", "jpg", "bmp"] },
    FormatInfo { ext: "mp4", name: "MPEG-4 Video", category: FormatCategory::Video, mime: "video/mp4", suggested_targets: &["mkv", "webm", "avi", "mov", "gif", "mp3", "wav", "flac"] },
    FormatInfo { ext: "mkv", name: "Matroska Video", category: FormatCategory::Video, mime: "video/x-matroska", suggested_targets: &["mp4", "webm", "avi", "mov", "gif", "mp3", "wav"] },
    FormatInfo { ext: "webm", name: "WebM Video", category: FormatCategory::Video, mime: "video/webm", suggested_targets: &["mp4", "mkv", "avi", "gif", "mp3", "opus", "wav"] },
    FormatInfo { ext: "avi", name: "Audio Video Interleave", category: FormatCategory::Video, mime: "video/x-msvideo", suggested_targets: &["mp4", "mkv", "webm", "mov", "mp3", "wav"] },
    FormatInfo { ext: "mov", name: "QuickTime Movie", category: FormatCategory::Video, mime: "video/quicktime", suggested_targets: &["mp4", "mkv", "webm", "gif", "mp3", "wav"] },
    FormatInfo { ext: "wmv", name: "Windows Media Video", category: FormatCategory::Video, mime: "video/x-ms-wmv", suggested_targets: &["mp4", "mkv", "webm", "mp3", "wma"] },
    FormatInfo { ext: "flv", name: "Flash Video", category: FormatCategory::Video, mime: "video/x-flv", suggested_targets: &["mp4", "mkv", "webm", "mp3"] },
    FormatInfo { ext: "m4v", name: "iTunes Video", category: FormatCategory::Video, mime: "video/x-m4v", suggested_targets: &["mp4", "mkv", "webm", "mp3"] },
    FormatInfo { ext: "3gp", name: "3GPP Video", category: FormatCategory::Video, mime: "video/3gpp", suggested_targets: &["mp4", "mkv", "mp3", "wav"] },
    FormatInfo { ext: "3gpp", name: "3GPP Video", category: FormatCategory::Video, mime: "video/3gpp", suggested_targets: &["mp4", "mkv", "mp3", "wav"] },
    FormatInfo { ext: "3g2", name: "3GPP2 Video", category: FormatCategory::Video, mime: "video/3gpp2", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "ts", name: "MPEG Transport Stream", category: FormatCategory::Video, mime: "video/mp2t", suggested_targets: &["mp4", "mkv", "webm", "mp3"] },
    FormatInfo { ext: "mts", name: "AVCHD Video", category: FormatCategory::Video, mime: "video/mp2t", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "m2ts", name: "Blu-ray BDAV Video", category: FormatCategory::Video, mime: "video/mp2t", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "vob", name: "DVD Video Object", category: FormatCategory::Video, mime: "video/dvd", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "ogv", name: "Ogg Video", category: FormatCategory::Video, mime: "video/ogg", suggested_targets: &["mp4", "webm", "mkv", "ogg"] },
    FormatInfo { ext: "mpg", name: "MPEG Video", category: FormatCategory::Video, mime: "video/mpeg", suggested_targets: &["mp4", "mkv", "webm", "mp3"] },
    FormatInfo { ext: "mpeg", name: "MPEG Video", category: FormatCategory::Video, mime: "video/mpeg", suggested_targets: &["mp4", "mkv", "webm", "mp3"] },
    FormatInfo { ext: "m2v", name: "MPEG-2 Video", category: FormatCategory::Video, mime: "video/mpeg", suggested_targets: &["mp4", "mkv"] },
    FormatInfo { ext: "bik", name: "Bink Video", category: FormatCategory::Video, mime: "video/vnd.radgametools.bink", suggested_targets: &["mp4", "mkv", "webm"] },
    FormatInfo { ext: "bik2", name: "Bink 2 Video", category: FormatCategory::Video, mime: "video/vnd.radgametools.bink", suggested_targets: &["mp4", "mkv"] },
    FormatInfo { ext: "rm", name: "RealMedia", category: FormatCategory::Video, mime: "application/vnd.rn-realmedia", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "rmvb", name: "RealMedia Variable Bitrate", category: FormatCategory::Video, mime: "application/vnd.rn-realmedia-vbr", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "f4v", name: "Flash MP4 Video", category: FormatCategory::Video, mime: "video/x-f4v", suggested_targets: &["mp4", "mkv"] },
    FormatInfo { ext: "asf", name: "Advanced Systems Format", category: FormatCategory::Video, mime: "video/x-ms-asf", suggested_targets: &["mp4", "wmv", "mp3"] },
    FormatInfo { ext: "y4m", name: "YUV4MPEG2 Video", category: FormatCategory::Video, mime: "video/x-raw-yuv", suggested_targets: &["mp4", "mkv", "webm"] },
    FormatInfo { ext: "wtv", name: "Windows TV Video", category: FormatCategory::Video, mime: "video/x-ms-wtv", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "dvr-ms", name: "Microsoft DVR Video", category: FormatCategory::Video, mime: "video/x-ms-dvr", suggested_targets: &["mp4", "mkv", "mp3"] },
    FormatInfo { ext: "divx", name: "DivX Video", category: FormatCategory::Video, mime: "video/x-divx", suggested_targets: &["mp4", "mkv", "avi", "mp3"] },
    FormatInfo { ext: "xvid", name: "Xvid Video", category: FormatCategory::Video, mime: "video/x-xvid", suggested_targets: &["mp4", "mkv", "avi", "mp3"] },
    FormatInfo { ext: "mxf", name: "Material Exchange Format", category: FormatCategory::Video, mime: "application/mxf", suggested_targets: &["mp4", "mkv", "mov"] },
    FormatInfo { ext: "nut", name: "NUT Video Container", category: FormatCategory::Video, mime: "video/x-nut", suggested_targets: &["mp4", "mkv", "webm"] },
    FormatInfo { ext: "ivf", name: "IVF Video Container", category: FormatCategory::Video, mime: "video/x-ivf", suggested_targets: &["mp4", "mkv", "webm"] },
    FormatInfo { ext: "h264", name: "Raw H.264 Video", category: FormatCategory::Video, mime: "video/h264", suggested_targets: &["mp4", "mkv", "mov"] },
    FormatInfo { ext: "hevc", name: "Raw HEVC Video", category: FormatCategory::Video, mime: "video/hevc", suggested_targets: &["mp4", "mkv", "mov"] },
    FormatInfo { ext: "vc1", name: "VC-1 Video", category: FormatCategory::Video, mime: "video/vc1", suggested_targets: &["mp4", "mkv"] },
    FormatInfo { ext: "apng", name: "Animated PNG", category: FormatCategory::Video, mime: "image/apng", suggested_targets: &["mp4", "webm", "gif", "png"] },
    FormatInfo { ext: "prores", name: "Apple ProRes Video", category: FormatCategory::Video, mime: "video/prores", suggested_targets: &["mp4", "mkv", "mov"] },
    FormatInfo { ext: "dnxhd", name: "Avid DNxHD Video", category: FormatCategory::Video, mime: "video/dnxhd", suggested_targets: &["mp4", "mkv", "mov"] },
    FormatInfo { ext: "mp3", name: "MPEG Audio Layer III", category: FormatCategory::Audio, mime: "audio/mpeg", suggested_targets: &["wav", "flac", "aac", "ogg", "opus", "m4a", "wma"] },
    FormatInfo { ext: "wav", name: "Waveform Audio", category: FormatCategory::Audio, mime: "audio/wav", suggested_targets: &["mp3", "flac", "aac", "ogg", "opus", "m4a", "wma", "aiff"] },
    FormatInfo { ext: "flac", name: "Free Lossless Audio Codec", category: FormatCategory::Audio, mime: "audio/flac", suggested_targets: &["mp3", "wav", "aac", "ogg", "opus", "m4a"] },
    FormatInfo { ext: "aac", name: "Advanced Audio Coding", category: FormatCategory::Audio, mime: "audio/aac", suggested_targets: &["mp3", "wav", "flac", "ogg", "opus", "m4a"] },
    FormatInfo { ext: "m4a", name: "Apple Lossless / AAC Audio", category: FormatCategory::Audio, mime: "audio/mp4", suggested_targets: &["mp3", "wav", "flac", "ogg", "opus", "aac"] },
    FormatInfo { ext: "m4b", name: "Audiobook M4B", category: FormatCategory::Audio, mime: "audio/mp4", suggested_targets: &["mp3", "m4a", "wav", "flac"] },
    FormatInfo { ext: "m4r", name: "iPhone Ringtone", category: FormatCategory::Audio, mime: "audio/mp4", suggested_targets: &["mp3", "wav", "m4a"] },
    FormatInfo { ext: "ogg", name: "Ogg Vorbis Audio", category: FormatCategory::Audio, mime: "audio/ogg", suggested_targets: &["mp3", "wav", "flac", "opus", "m4a", "aac"] },
    FormatInfo { ext: "oga", name: "Ogg Audio", category: FormatCategory::Audio, mime: "audio/ogg", suggested_targets: &["mp3", "wav", "flac", "opus"] },
    FormatInfo { ext: "opus", name: "Opus Audio", category: FormatCategory::Audio, mime: "audio/opus", suggested_targets: &["mp3", "wav", "flac", "ogg", "m4a", "aac"] },
    FormatInfo { ext: "wma", name: "Windows Media Audio", category: FormatCategory::Audio, mime: "audio/x-ms-wma", suggested_targets: &["mp3", "wav", "flac", "aac", "ogg"] },
    FormatInfo { ext: "aiff", name: "Audio Interchange File Format", category: FormatCategory::Audio, mime: "audio/x-aiff", suggested_targets: &["mp3", "wav", "flac", "m4a"] },
    FormatInfo { ext: "aif", name: "Audio Interchange File Format", category: FormatCategory::Audio, mime: "audio/x-aiff", suggested_targets: &["mp3", "wav", "flac", "m4a"] },
    FormatInfo { ext: "ape", name: "Monkey's Audio", category: FormatCategory::Audio, mime: "audio/x-ape", suggested_targets: &["flac", "mp3", "wav", "m4a"] },
    FormatInfo { ext: "alac", name: "Apple Lossless Audio", category: FormatCategory::Audio, mime: "audio/x-alac", suggested_targets: &["flac", "wav", "mp3", "m4a"] },
    FormatInfo { ext: "ac3", name: "Dolby Digital Audio", category: FormatCategory::Audio, mime: "audio/ac3", suggested_targets: &["mp3", "wav", "flac", "aac"] },
    FormatInfo { ext: "eac3", name: "Dolby Digital Plus Audio", category: FormatCategory::Audio, mime: "audio/eac3", suggested_targets: &["mp3", "wav", "flac", "ac3"] },
    FormatInfo { ext: "dts", name: "DTS Coherent Acoustics", category: FormatCategory::Audio, mime: "audio/vnd.dts", suggested_targets: &["wav", "flac", "ac3", "mp3"] },
    FormatInfo { ext: "amr", name: "Adaptive Multi-Rate Audio", category: FormatCategory::Audio, mime: "audio/amr", suggested_targets: &["mp3", "wav", "ogg"] },
    FormatInfo { ext: "mid", name: "MIDI Audio", category: FormatCategory::Audio, mime: "audio/midi", suggested_targets: &["wav", "mp3", "flac"] },
    FormatInfo { ext: "midi", name: "MIDI Audio", category: FormatCategory::Audio, mime: "audio/midi", suggested_targets: &["wav", "mp3", "flac"] },
    FormatInfo { ext: "wv", name: "WavPack Lossless Audio", category: FormatCategory::Audio, mime: "audio/x-wavpack", suggested_targets: &["flac", "wav", "mp3"] },
    FormatInfo { ext: "cda", name: "CD Audio Track", category: FormatCategory::Audio, mime: "application/x-cdf", suggested_targets: &["flac", "wav", "mp3"] },
    FormatInfo { ext: "dtshd", name: "DTS-HD Master Audio", category: FormatCategory::Audio, mime: "audio/vnd.dts.hd", suggested_targets: &["wav", "flac", "ac3", "mp3"] },
    FormatInfo { ext: "awb", name: "AMR Wideband Audio", category: FormatCategory::Audio, mime: "audio/amr-wb", suggested_targets: &["mp3", "wav", "ogg"] },
    FormatInfo { ext: "gsm", name: "GSM Audio", category: FormatCategory::Audio, mime: "audio/gsm", suggested_targets: &["mp3", "wav", "ogg"] },
    FormatInfo { ext: "vox", name: "Dialogic VOX Audio", category: FormatCategory::Audio, mime: "audio/vox", suggested_targets: &["mp3", "wav"] },
    FormatInfo { ext: "mod", name: "ProTracker Module", category: FormatCategory::Audio, mime: "audio/x-mod", suggested_targets: &["wav", "mp3", "flac", "ogg"] },
    FormatInfo { ext: "s3m", name: "ScreamTracker 3 Module", category: FormatCategory::Audio, mime: "audio/x-s3m", suggested_targets: &["wav", "mp3", "flac", "ogg"] },
    FormatInfo { ext: "xm", name: "FastTracker Extended Module", category: FormatCategory::Audio, mime: "audio/x-xm", suggested_targets: &["wav", "mp3", "flac", "ogg"] },
    FormatInfo { ext: "it", name: "Impulse Tracker Module", category: FormatCategory::Audio, mime: "audio/x-it", suggested_targets: &["wav", "mp3", "flac", "ogg"] },
    FormatInfo { ext: "mka", name: "Matroska Audio", category: FormatCategory::Audio, mime: "audio/x-matroska", suggested_targets: &["mp3", "wav", "flac", "ogg", "m4a"] },
    FormatInfo { ext: "tta", name: "True Audio Lossless", category: FormatCategory::Audio, mime: "audio/x-tta", suggested_targets: &["flac", "wav", "mp3"] },
    FormatInfo { ext: "dsf", name: "DSD Stream File", category: FormatCategory::Audio, mime: "audio/x-dsf", suggested_targets: &["flac", "wav", "mp3"] },
    FormatInfo { ext: "dff", name: "DSD Interchange File", category: FormatCategory::Audio, mime: "audio/x-dff", suggested_targets: &["flac", "wav", "mp3"] },
    FormatInfo { ext: "ra", name: "RealAudio", category: FormatCategory::Audio, mime: "audio/x-realaudio", suggested_targets: &["mp3", "wav", "ogg"] },
    FormatInfo { ext: "voc", name: "Creative Voice File", category: FormatCategory::Audio, mime: "audio/x-voc", suggested_targets: &["wav", "mp3", "flac"] },
    FormatInfo { ext: "caf", name: "Core Audio Format", category: FormatCategory::Audio, mime: "audio/x-caf", suggested_targets: &["wav", "mp3", "flac", "m4a"] },
    FormatInfo { ext: "au", name: "Sun Audio", category: FormatCategory::Audio, mime: "audio/basic", suggested_targets: &["wav", "mp3", "flac"] },
    FormatInfo { ext: "spx", name: "Speex Audio", category: FormatCategory::Audio, mime: "audio/speex", suggested_targets: &["wav", "mp3", "ogg", "opus"] },
    FormatInfo { ext: "w64", name: "Sony Wave64 Audio", category: FormatCategory::Audio, mime: "audio/x-w64", suggested_targets: &["wav", "flac", "mp3"] },
    FormatInfo { ext: "pdf", name: "Portable Document Format", category: FormatCategory::Document, mime: "application/pdf", suggested_targets: &["png", "jpg", "docx", "txt", "html"] },
    FormatInfo { ext: "docx", name: "Microsoft Word OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", suggested_targets: &["pdf", "odt", "txt", "html", "md", "rtf"] },
    FormatInfo { ext: "doc", name: "Microsoft Word Document", category: FormatCategory::Document, mime: "application/msword", suggested_targets: &["docx", "pdf", "odt", "txt", "html"] },
    FormatInfo { ext: "xlsx", name: "Microsoft Excel OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", suggested_targets: &["pdf", "ods", "csv", "tsv"] },
    FormatInfo { ext: "xls", name: "Microsoft Excel Spreadsheet", category: FormatCategory::Document, mime: "application/vnd.ms-excel", suggested_targets: &["xlsx", "pdf", "ods", "csv", "tsv"] },
    FormatInfo { ext: "pptx", name: "Microsoft PowerPoint OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation", suggested_targets: &["pdf", "odp", "png", "jpg"] },
    FormatInfo { ext: "ppt", name: "Microsoft PowerPoint Presentation", category: FormatCategory::Document, mime: "application/vnd.ms-powerpoint", suggested_targets: &["pptx", "pdf", "odp"] },
    FormatInfo { ext: "odt", name: "OpenDocument Text", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.text", suggested_targets: &["docx", "pdf", "txt", "html", "md"] },
    FormatInfo { ext: "ods", name: "OpenDocument Spreadsheet", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.spreadsheet", suggested_targets: &["xlsx", "pdf", "csv", "tsv"] },
    FormatInfo { ext: "odp", name: "OpenDocument Presentation", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.presentation", suggested_targets: &["pptx", "pdf", "png"] },
    FormatInfo { ext: "rtf", name: "Rich Text Format", category: FormatCategory::Document, mime: "application/rtf", suggested_targets: &["docx", "pdf", "odt", "txt", "html"] },
    FormatInfo { ext: "txt", name: "Plain Text Document", category: FormatCategory::Document, mime: "text/plain", suggested_targets: &["pdf", "md", "html", "docx"] },
    FormatInfo { ext: "md", name: "Markdown Document", category: FormatCategory::Document, mime: "text/markdown", suggested_targets: &["html", "pdf", "docx", "txt", "epub"] },
    FormatInfo { ext: "markdown", name: "Markdown Document", category: FormatCategory::Document, mime: "text/markdown", suggested_targets: &["html", "pdf", "docx", "txt", "epub"] },
    FormatInfo { ext: "html", name: "HyperText Markup Language", category: FormatCategory::Document, mime: "text/html", suggested_targets: &["pdf", "md", "txt", "docx", "png"] },
    FormatInfo { ext: "htm", name: "HyperText Markup Language", category: FormatCategory::Document, mime: "text/html", suggested_targets: &["pdf", "md", "txt", "docx", "png"] },
    FormatInfo { ext: "epub", name: "Electronic Publication E-Book", category: FormatCategory::Document, mime: "application/epub+zip", suggested_targets: &["pdf", "mobi", "azw3", "txt", "html"] },
    FormatInfo { ext: "mobi", name: "Mobipocket E-Book", category: FormatCategory::Document, mime: "application/x-mobipocket-ebook", suggested_targets: &["epub", "pdf", "azw3", "txt"] },
    FormatInfo { ext: "azw3", name: "Kindle Format 8 E-Book", category: FormatCategory::Document, mime: "application/vnd.amazon.ebook", suggested_targets: &["epub", "pdf", "mobi"] },
    FormatInfo { ext: "pages", name: "Apple Pages Document", category: FormatCategory::Document, mime: "application/x-iwork-pages-sffpages", suggested_targets: &["pdf", "docx", "txt"] },
    FormatInfo { ext: "numbers", name: "Apple Numbers Spreadsheet", category: FormatCategory::Document, mime: "application/x-iwork-numbers-sffnumbers", suggested_targets: &["pdf", "xlsx", "csv"] },
    FormatInfo { ext: "key", name: "Apple Keynote Presentation", category: FormatCategory::Document, mime: "application/x-iwork-keynote-sffkey", suggested_targets: &["pdf", "pptx"] },
    FormatInfo { ext: "tex", name: "LaTeX Document", category: FormatCategory::Document, mime: "application/x-tex", suggested_targets: &["pdf", "html", "md", "docx"] },
    FormatInfo { ext: "latex", name: "LaTeX Document", category: FormatCategory::Document, mime: "application/x-latex", suggested_targets: &["pdf", "html", "md", "docx"] },
    FormatInfo { ext: "typ", name: "Typst Document", category: FormatCategory::Document, mime: "text/x-typst", suggested_targets: &["pdf", "png", "svg"] },
    FormatInfo { ext: "dot", name: "Word Template (Legacy)", category: FormatCategory::Document, mime: "application/msword", suggested_targets: &["docx", "pdf", "txt"] },
    FormatInfo { ext: "dotx", name: "Word Template OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.template", suggested_targets: &["docx", "pdf", "txt"] },
    FormatInfo { ext: "docm", name: "Word Macro Document", category: FormatCategory::Document, mime: "application/vnd.ms-word.document.macroEnabled.12", suggested_targets: &["docx", "pdf", "txt"] },
    FormatInfo { ext: "ott", name: "OpenDocument Text Template", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.text-template", suggested_targets: &["odt", "docx", "pdf"] },
    FormatInfo { ext: "fodt", name: "Flat OpenDocument Text", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.text", suggested_targets: &["odt", "docx", "pdf", "txt"] },
    FormatInfo { ext: "xlt", name: "Excel Template (Legacy)", category: FormatCategory::Document, mime: "application/vnd.ms-excel", suggested_targets: &["xlsx", "pdf", "csv"] },
    FormatInfo { ext: "xltx", name: "Excel Template OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.template", suggested_targets: &["xlsx", "pdf", "csv"] },
    FormatInfo { ext: "xlsm", name: "Excel Macro Spreadsheet", category: FormatCategory::Document, mime: "application/vnd.ms-excel.sheet.macroEnabled.12", suggested_targets: &["xlsx", "pdf", "csv"] },
    FormatInfo { ext: "xlsb", name: "Excel Binary Spreadsheet", category: FormatCategory::Document, mime: "application/vnd.ms-excel.sheet.binary.macroEnabled.12", suggested_targets: &["xlsx", "pdf", "csv"] },
    FormatInfo { ext: "ots", name: "OpenDocument Spreadsheet Template", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.spreadsheet-template", suggested_targets: &["ods", "xlsx", "pdf"] },
    FormatInfo { ext: "fods", name: "Flat OpenDocument Spreadsheet", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.spreadsheet", suggested_targets: &["ods", "xlsx", "csv", "pdf"] },
    FormatInfo { ext: "pot", name: "PowerPoint Template (Legacy)", category: FormatCategory::Document, mime: "application/vnd.ms-powerpoint", suggested_targets: &["pptx", "pdf"] },
    FormatInfo { ext: "potx", name: "PowerPoint Template OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.presentationml.template", suggested_targets: &["pptx", "pdf"] },
    FormatInfo { ext: "pptm", name: "PowerPoint Macro Presentation", category: FormatCategory::Document, mime: "application/vnd.ms-powerpoint.presentation.macroEnabled.12", suggested_targets: &["pptx", "pdf"] },
    FormatInfo { ext: "pps", name: "PowerPoint Slideshow (Legacy)", category: FormatCategory::Document, mime: "application/vnd.ms-powerpoint", suggested_targets: &["pptx", "pdf"] },
    FormatInfo { ext: "ppsx", name: "PowerPoint Slideshow OpenXML", category: FormatCategory::Document, mime: "application/vnd.openxmlformats-officedocument.presentationml.slideshow", suggested_targets: &["pptx", "pdf"] },
    FormatInfo { ext: "otp", name: "OpenDocument Presentation Template", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.presentation-template", suggested_targets: &["odp", "pptx", "pdf"] },
    FormatInfo { ext: "fodp", name: "Flat OpenDocument Presentation", category: FormatCategory::Document, mime: "application/vnd.oasis.opendocument.presentation", suggested_targets: &["odp", "pptx", "pdf"] },
    FormatInfo { ext: "wpd", name: "WordPerfect Document", category: FormatCategory::Document, mime: "application/x-wpd", suggested_targets: &["docx", "pdf", "txt"] },
    FormatInfo { ext: "wps", name: "Microsoft Works Document", category: FormatCategory::Document, mime: "application/vnd.ms-works", suggested_targets: &["docx", "pdf", "txt"] },
    FormatInfo { ext: "fb2", name: "FictionBook E-Book", category: FormatCategory::Document, mime: "application/x-fictionbook+xml", suggested_targets: &["epub", "pdf", "txt", "html"] },
    FormatInfo { ext: "cbz", name: "Comic Book Zip", category: FormatCategory::Document, mime: "application/x-cbz", suggested_targets: &["pdf", "epub", "zip"] },
    FormatInfo { ext: "cbr", name: "Comic Book Rar", category: FormatCategory::Document, mime: "application/x-cbr", suggested_targets: &["pdf", "cbz", "zip"] },
    FormatInfo { ext: "cbt", name: "Comic Book Tar", category: FormatCategory::Document, mime: "application/x-cbt", suggested_targets: &["pdf", "cbz", "zip"] },
    FormatInfo { ext: "cb7", name: "Comic Book 7z", category: FormatCategory::Document, mime: "application/x-cb7", suggested_targets: &["pdf", "cbz", "zip"] },
    FormatInfo { ext: "djvu", name: "DjVu Document", category: FormatCategory::Document, mime: "image/vnd.djvu", suggested_targets: &["pdf", "txt", "html"] },
    FormatInfo { ext: "chm", name: "Compiled HTML Help", category: FormatCategory::Document, mime: "application/vnd.ms-htmlhelp", suggested_targets: &["pdf", "html", "txt"] },
    FormatInfo { ext: "rst", name: "reStructuredText", category: FormatCategory::Document, mime: "text/x-rst", suggested_targets: &["html", "pdf", "md", "docx"] },
    FormatInfo { ext: "adoc", name: "AsciiDoc Document", category: FormatCategory::Document, mime: "text/asciidoc", suggested_targets: &["html", "pdf", "md", "docx"] },
    FormatInfo { ext: "asciidoc", name: "AsciiDoc Document", category: FormatCategory::Document, mime: "text/asciidoc", suggested_targets: &["html", "pdf", "md"] },
    FormatInfo { ext: "org", name: "Emacs Org Document", category: FormatCategory::Document, mime: "text/org", suggested_targets: &["html", "pdf", "md", "txt"] },
    FormatInfo { ext: "xhtml", name: "XHTML Document", category: FormatCategory::Document, mime: "application/xhtml+xml", suggested_targets: &["pdf", "html", "md", "txt"] },
    FormatInfo { ext: "mhtml", name: "MIME HTML Archive", category: FormatCategory::Document, mime: "multipart/related", suggested_targets: &["html", "pdf", "txt"] },
    FormatInfo { ext: "keynote", name: "Apple Keynote Presentation", category: FormatCategory::Document, mime: "application/x-iwork-keynote-sffkey", suggested_targets: &["pdf", "pptx"] },
    FormatInfo { ext: "json", name: "JavaScript Object Notation", category: FormatCategory::Data, mime: "application/json", suggested_targets: &["yaml", "toml", "xml", "csv", "ron", "html"] },
    FormatInfo { ext: "json5", name: "JSON5 Data", category: FormatCategory::Data, mime: "application/json5", suggested_targets: &["json", "yaml", "toml"] },
    FormatInfo { ext: "jsonc", name: "JSON with Comments", category: FormatCategory::Data, mime: "application/json", suggested_targets: &["json", "yaml", "toml"] },
    FormatInfo { ext: "yaml", name: "YAML Ain't Markup Language", category: FormatCategory::Data, mime: "application/x-yaml", suggested_targets: &["json", "toml", "xml", "ron"] },
    FormatInfo { ext: "yml", name: "YAML Ain't Markup Language", category: FormatCategory::Data, mime: "application/x-yaml", suggested_targets: &["json", "toml", "xml", "ron"] },
    FormatInfo { ext: "toml", name: "Tom's Obvious Minimal Language", category: FormatCategory::Data, mime: "application/toml", suggested_targets: &["json", "yaml", "xml", "ron"] },
    FormatInfo { ext: "xml", name: "Extensible Markup Language", category: FormatCategory::Data, mime: "application/xml", suggested_targets: &["json", "yaml", "toml", "csv"] },
    FormatInfo { ext: "csv", name: "Comma-Separated Values", category: FormatCategory::Data, mime: "text/csv", suggested_targets: &["json", "tsv", "xlsx", "yaml", "xml", "html"] },
    FormatInfo { ext: "tsv", name: "Tab-Separated Values", category: FormatCategory::Data, mime: "text/tab-separated-values", suggested_targets: &["csv", "json", "xlsx", "yaml"] },
    FormatInfo { ext: "ron", name: "Rusty Object Notation", category: FormatCategory::Data, mime: "application/x-ron", suggested_targets: &["json", "yaml", "toml"] },
    FormatInfo { ext: "plist", name: "Apple Property List", category: FormatCategory::Data, mime: "application/x-plist", suggested_targets: &["json", "yaml", "xml"] },
    FormatInfo { ext: "ini", name: "Configuration File", category: FormatCategory::Data, mime: "text/plain", suggested_targets: &["json", "toml", "yaml"] },
    FormatInfo { ext: "env", name: "Environment File", category: FormatCategory::Data, mime: "text/plain", suggested_targets: &["json", "yaml", "toml"] },
    FormatInfo { ext: "ndjson", name: "Newline Delimited JSON", category: FormatCategory::Data, mime: "application/x-ndjson", suggested_targets: &["json", "csv", "yaml"] },
    FormatInfo { ext: "kdl", name: "KDL Document Language", category: FormatCategory::Data, mime: "application/kdl", suggested_targets: &["json", "yaml", "toml", "xml"] },
    FormatInfo { ext: "properties", name: "Java Properties File", category: FormatCategory::Data, mime: "text/x-java-properties", suggested_targets: &["json", "yaml", "toml", "ini"] },
    FormatInfo { ext: "psv", name: "Pipe-Separated Values", category: FormatCategory::Data, mime: "text/psv", suggested_targets: &["csv", "json", "tsv"] },
    FormatInfo { ext: "parquet", name: "Apache Parquet Columnar", category: FormatCategory::Data, mime: "application/x-parquet", suggested_targets: &["csv", "json"] },
    FormatInfo { ext: "arrow", name: "Apache Arrow IPC", category: FormatCategory::Data, mime: "application/x-arrow", suggested_targets: &["csv", "json"] },
    FormatInfo { ext: "sqlite", name: "SQLite Database", category: FormatCategory::Data, mime: "application/x-sqlite3", suggested_targets: &["csv", "json"] },
    FormatInfo { ext: "db", name: "Database File", category: FormatCategory::Data, mime: "application/x-sqlite3", suggested_targets: &["csv", "json"] },
    FormatInfo { ext: "msgpack", name: "MessagePack Binary", category: FormatCategory::Data, mime: "application/msgpack", suggested_targets: &["json", "yaml", "csv"] },
    FormatInfo { ext: "cbor", name: "CBOR Binary Data", category: FormatCategory::Data, mime: "application/cbor", suggested_targets: &["json", "yaml", "csv"] },
    FormatInfo { ext: "bson", name: "Binary JSON", category: FormatCategory::Data, mime: "application/bson", suggested_targets: &["json", "yaml", "csv"] },
    FormatInfo { ext: "obj", name: "Wavefront 3D Object", category: FormatCategory::Model3D, mime: "model/obj", suggested_targets: &["stl", "ply", "gltf", "glb", "3mf"] },
    FormatInfo { ext: "stl", name: "STereoLithography 3D", category: FormatCategory::Model3D, mime: "model/stl", suggested_targets: &["obj", "ply", "3mf", "glb"] },
    FormatInfo { ext: "ply", name: "Polygon File Format", category: FormatCategory::Model3D, mime: "model/ply", suggested_targets: &["obj", "stl", "gltf", "glb"] },
    FormatInfo { ext: "gltf", name: "GL Transmission Format", category: FormatCategory::Model3D, mime: "model/gltf+json", suggested_targets: &["glb", "obj", "stl", "ply", "usdz"] },
    FormatInfo { ext: "glb", name: "Binary GLTF", category: FormatCategory::Model3D, mime: "model/gltf-binary", suggested_targets: &["gltf", "obj", "stl", "ply", "usdz"] },
    FormatInfo { ext: "fbx", name: "Filmbox 3D Asset", category: FormatCategory::Model3D, mime: "application/octet-stream", suggested_targets: &["gltf", "glb", "obj", "stl"] },
    FormatInfo { ext: "3mf", name: "3D Manufacturing Format", category: FormatCategory::Model3D, mime: "model/3mf", suggested_targets: &["stl", "obj", "ply", "glb"] },
    FormatInfo { ext: "usdz", name: "Universal Scene Description Zip", category: FormatCategory::Model3D, mime: "model/vnd.usdz+zip", suggested_targets: &["glb", "gltf", "obj"] },
    FormatInfo { ext: "off", name: "Object File Format", category: FormatCategory::Model3D, mime: "model/off", suggested_targets: &["obj", "stl", "ply"] },
    FormatInfo { ext: "dae", name: "Collada Digital Asset", category: FormatCategory::Model3D, mime: "model/vnd.collada+xml", suggested_targets: &["glb", "gltf", "obj", "stl"] },
    FormatInfo { ext: "3ds", name: "3D Studio Scene", category: FormatCategory::Model3D, mime: "image/x-3ds", suggested_targets: &["obj", "stl", "glb", "gltf"] },
    FormatInfo { ext: "blend", name: "Blender Scene", category: FormatCategory::Model3D, mime: "application/x-blender", suggested_targets: &["glb", "obj", "stl", "fbx"] },
    FormatInfo { ext: "x3d", name: "Extensible 3D Graphics", category: FormatCategory::Model3D, mime: "model/x3d+xml", suggested_targets: &["glb", "obj", "stl"] },
    FormatInfo { ext: "step", name: "STEP CAD Model", category: FormatCategory::Model3D, mime: "model/step", suggested_targets: &["stl", "obj", "ply"] },
    FormatInfo { ext: "stp", name: "STEP CAD Model", category: FormatCategory::Model3D, mime: "model/step", suggested_targets: &["stl", "obj", "ply"] },
    FormatInfo { ext: "iges", name: "IGES CAD Model", category: FormatCategory::Model3D, mime: "model/iges", suggested_targets: &["stl", "obj", "ply"] },
    FormatInfo { ext: "igs", name: "IGES CAD Model", category: FormatCategory::Model3D, mime: "model/iges", suggested_targets: &["stl", "obj", "ply"] },
    FormatInfo { ext: "dxf", name: "Drawing Exchange Format", category: FormatCategory::Model3D, mime: "image/vnd.dxf", suggested_targets: &["obj", "stl", "svg"] },
    FormatInfo { ext: "usda", name: "USD ASCII Scene", category: FormatCategory::Model3D, mime: "model/vnd.usd+plain", suggested_targets: &["usdz", "glb", "obj"] },
    FormatInfo { ext: "usdc", name: "USD Binary Scene", category: FormatCategory::Model3D, mime: "model/vnd.usd+binary", suggested_targets: &["usdz", "glb", "obj"] },
    FormatInfo { ext: "zip", name: "Zip Compressed Archive", category: FormatCategory::Archive, mime: "application/zip", suggested_targets: &["tar", "tar.gz", "tar.xz", "7z"] },
    FormatInfo { ext: "tar", name: "Tarball Archive", category: FormatCategory::Archive, mime: "application/x-tar", suggested_targets: &["zip", "tar.gz", "tar.xz"] },
    FormatInfo { ext: "gz", name: "Gzip Compressed File", category: FormatCategory::Archive, mime: "application/gzip", suggested_targets: &["tar", "zip"] },
    FormatInfo { ext: "tgz", name: "Gzip Tarball Archive", category: FormatCategory::Archive, mime: "application/gzip", suggested_targets: &["zip", "tar", "tar.xz"] },
    FormatInfo { ext: "7z", name: "7-Zip Compressed Archive", category: FormatCategory::Archive, mime: "application/x-7z-compressed", suggested_targets: &["zip", "tar", "tar.gz"] },
    FormatInfo { ext: "rar", name: "WinRAR Archive", category: FormatCategory::Archive, mime: "application/vnd.rar", suggested_targets: &["zip", "tar", "7z"] },
    FormatInfo { ext: "bz2", name: "Bzip2 Compressed File", category: FormatCategory::Archive, mime: "application/x-bzip2", suggested_targets: &["zip", "tar", "gz"] },
    FormatInfo { ext: "xz", name: "XZ Compressed File", category: FormatCategory::Archive, mime: "application/x-xz", suggested_targets: &["zip", "tar", "gz"] },
    FormatInfo { ext: "zst", name: "Zstandard Compressed File", category: FormatCategory::Archive, mime: "application/zstd", suggested_targets: &["zip", "tar", "gz"] },
    FormatInfo { ext: "lz4", name: "LZ4 Compressed File", category: FormatCategory::Archive, mime: "application/x-lz4", suggested_targets: &["zip", "tar", "gz"] },
    FormatInfo { ext: "iso", name: "ISO Disc Image", category: FormatCategory::Archive, mime: "application/x-iso9660-image", suggested_targets: &["zip", "tar"] },
    FormatInfo { ext: "cab", name: "Windows Cabinet Archive", category: FormatCategory::Archive, mime: "application/vnd.ms-cab-compressed", suggested_targets: &["zip", "tar"] },
    FormatInfo { ext: "tbz2", name: "Bzip2 Tarball Archive", category: FormatCategory::Archive, mime: "application/x-bzip2", suggested_targets: &["zip", "tar", "tar.gz"] },
    FormatInfo { ext: "txz", name: "XZ Tarball Archive", category: FormatCategory::Archive, mime: "application/x-xz", suggested_targets: &["zip", "tar", "tar.gz"] },
    FormatInfo { ext: "tzst", name: "Zstandard Tarball Archive", category: FormatCategory::Archive, mime: "application/zstd", suggested_targets: &["zip", "tar", "tar.gz"] },
    FormatInfo { ext: "ttf", name: "TrueType Font", category: FormatCategory::Font, mime: "font/ttf", suggested_targets: &["woff", "woff2", "otf", "eot"] },
    FormatInfo { ext: "otf", name: "OpenType Font", category: FormatCategory::Font, mime: "font/otf", suggested_targets: &["woff", "woff2", "ttf", "eot"] },
    FormatInfo { ext: "woff", name: "Web Open Font Format", category: FormatCategory::Font, mime: "font/woff", suggested_targets: &["woff2", "ttf", "otf"] },
    FormatInfo { ext: "woff2", name: "Web Open Font Format 2", category: FormatCategory::Font, mime: "font/woff2", suggested_targets: &["woff", "ttf", "otf"] },
    FormatInfo { ext: "eot", name: "Embedded OpenType Font", category: FormatCategory::Font, mime: "application/vnd.ms-fontobject", suggested_targets: &["ttf", "woff", "woff2"] },
    FormatInfo { ext: "dfont", name: "Mac Data Fork Font", category: FormatCategory::Font, mime: "font/dfont", suggested_targets: &["ttf", "otf", "woff"] },
    FormatInfo { ext: "pfa", name: "PostScript Type1 ASCII", category: FormatCategory::Font, mime: "application/x-font-type1", suggested_targets: &["ttf", "otf", "woff"] },
    FormatInfo { ext: "pfb", name: "PostScript Type1 Binary", category: FormatCategory::Font, mime: "application/x-font-type1", suggested_targets: &["ttf", "otf", "woff"] },
    FormatInfo { ext: "srt", name: "SubRip Subtitle", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["vtt", "ass", "ssa", "lrc", "txt"] },
    FormatInfo { ext: "vtt", name: "WebVTT Subtitle", category: FormatCategory::Subtitle, mime: "text/vtt", suggested_targets: &["srt", "ass", "ssa", "txt"] },
    FormatInfo { ext: "ass", name: "Advanced SubStation Alpha", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["srt", "vtt", "ssa", "txt"] },
    FormatInfo { ext: "ssa", name: "SubStation Alpha", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["srt", "vtt", "ass", "txt"] },
    FormatInfo { ext: "lrc", name: "Lyric File", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["srt", "vtt", "txt"] },
    FormatInfo { ext: "sub", name: "MicroDVD Subtitle", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["srt", "vtt", "txt"] },
    FormatInfo { ext: "sbv", name: "YouTube SBV Subtitle", category: FormatCategory::Subtitle, mime: "text/plain", suggested_targets: &["srt", "vtt", "txt"] },
    FormatInfo { ext: "ttml", name: "Timed Text Markup", category: FormatCategory::Subtitle, mime: "application/ttml+xml", suggested_targets: &["srt", "vtt", "txt"] },
    FormatInfo { ext: "smi", name: "SAMI Subtitle", category: FormatCategory::Subtitle, mime: "application/smil", suggested_targets: &["srt", "vtt", "txt"] },
];
pub fn find_format(ext: &str) -> Option<&'static FormatInfo> {
    let clean_ext = ext.trim_start_matches('.').to_lowercase();
    FORMAT_DATABASE.iter().find(|f| f.ext == clean_ext)
}
pub fn detect_format_from_path<P: AsRef<Path>>(path: P) -> Option<&'static FormatInfo> {
    let p = path.as_ref();
    let ext = p.extension()?.to_str()?;
    find_format(ext)
}
pub fn get_suggested_conversions(ext: &str) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    if let Some(info) = find_format(ext) {
        out.extend_from_slice(info.suggested_targets);
        if matches!(info.category, FormatCategory::Image | FormatCategory::Video) && info.ext != "gif" && !out.contains(&"gif") {
            out.push("gif");
        }
    }
    out
}
